import Anthropic from "@anthropic-ai/sdk";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { SPEC_SECTIONS } from "../../../lib/spec-sections";
import type { LLMClient } from "../../../lib/llm-client";

/**
 * E7-S1 — End-to-end happy-path verification
 *
 * Drives the full backend loop using a scripted fake LLMClient (per the
 * E2-S3 abstraction) instead of a real AI provider:
 *
 *   create workspace -> project -> interview to convergence
 *   -> generate spec -> fetch latest
 *
 * No real API calls are made. The fake client is injected by mocking
 * createLLMClient(), so InterviewEngine and generateSpec() run for real —
 * only the AI provider call itself is faked.
 */

// ---------------------------------------------------------------------
// Scripted fake LLM client
// ---------------------------------------------------------------------

/**
 * Returns a fresh fake LLMClient. Each call to createMessage():
 *  - If asked for the "update_interview" tool: satisfies exactly one more
 *    spec section per call (in SPEC_SECTIONS order), until all are done.
 *  - If asked for the "emit_spec" tool: returns a complete fake spec.
 *
 * This stays in sync automatically with however many sections
 * SPEC_SECTIONS actually has — nothing is hardcoded.
 */
function createScriptedFakeLLMClient(): LLMClient {
  return {
    async createMessage({ systemPrompt, toolChoice }) {
      const toolName =
        toolChoice && toolChoice.type === "tool" ? toolChoice.name : undefined;

      if (toolName === "emit_spec") {
        return {
          id: "fake_spec_msg",
          type: "message",
          role: "assistant",
          content: [
            {
              type: "tool_use",
              id: "fake_tool_emit_spec",
              name: "emit_spec",
              input: {
                markdown: "# Fake E2E Spec\n\nGenerated by the scripted fake client for the E7-S1 test.",
                sections: Object.fromEntries(
                  SPEC_SECTIONS.map((s) => [s.id, `Fake content for ${s.label}`])
                ),
              },
            },
          ],
          model: "fake-scripted-model",
          stop_reason: "tool_use",
          stop_sequence: null,
          usage: { input_tokens: 0, output_tokens: 0 },
        } as Anthropic.Message;
      }

      // Interview turn: the real InterviewEngine's system prompt lists the
      // still-unsatisfied sections as "(id: xxx)". Satisfy the first one
      // mentioned. This reads real state from the prompt instead of relying
      // on a counter, so it works correctly even though a brand-new fake
      // client instance is created on every chat turn.
      const match = systemPrompt.match(/\(id:\s*([a-zA-Z0-9_-]+)\)/);
      const nextSectionId = match ? match[1] : SPEC_SECTIONS[0].id;

      return {
        id: `fake_interview_msg_${nextSectionId}`,
        type: "message",
        role: "assistant",
        content: [
          {
            type: "tool_use",
            id: `fake_tool_update_interview_${nextSectionId}`,
            name: "update_interview",
            input: {
              satisfied_section_ids: [nextSectionId],
              next_question: `Fake question about ${nextSectionId}`,
            },
          },
        ],
        model: "fake-scripted-model",
        stop_reason: "tool_use",
        stop_sequence: null,
        usage: { input_tokens: 0, output_tokens: 0 },
      } as Anthropic.Message;
    },
  };
}

// ---------------------------------------------------------------------
// Mocks: DB-layer repository functions stay mocked (same pattern as the
// existing routes.test.ts), but the LLM client is the scripted fake —
// InterviewEngine and generateSpec run for real against it.
// ---------------------------------------------------------------------

const repository = vi.hoisted(() => ({
  createWorkspace: vi.fn(),
  getWorkspaceByMagicToken: vi.fn(),
  getProjectInWorkspace: vi.fn(),
  createProject: vi.fn(),
  getOrCreateConversation: vi.fn(),
  saveConversationTurn: vi.fn(),
  createSpecVersion: vi.fn(),
  getLatestSpec: vi.fn(),
}));

vi.mock("../../../lib/workspace", () => ({
  createWorkspace: repository.createWorkspace,
  getWorkspaceByMagicToken: repository.getWorkspaceByMagicToken,
}));

vi.mock("../../../lib/project", () => ({
  getProjectInWorkspace: repository.getProjectInWorkspace,
  createProject: repository.createProject,
}));

vi.mock("../../../lib/conversation", () => ({
  getOrCreateConversation: repository.getOrCreateConversation,
  saveConversationTurn: repository.saveConversationTurn,
}));

vi.mock("../../../lib/spec", () => ({
  createSpecVersion: repository.createSpecVersion,
  getLatestSpec: repository.getLatestSpec,
}));

// createLLMClient always returns our scripted fake, regardless of the key passed in.
vi.mock("../../../lib/llm-client", async () => {
  const actual = await vi.importActual<typeof import("../../../lib/llm-client")>(
    "../../../lib/llm-client"
  );
  return {
    ...actual,
    createLLMClient: vi.fn(() => createScriptedFakeLLMClient()),
  };
});

// ---------------------------------------------------------------------
// Test
// ---------------------------------------------------------------------

import { POST as createWorkspaceRoute } from "../api/workspaces/route";
import { POST as createProjectRoute } from "../api/projects/route";
import { POST as chatRoute } from "../api/chat/route";
import { GET as getSpecRoute, POST as generateSpecRoute } from "../api/spec/route";

function request(method: string, path: string, options: {
  token?: string;
  aiKey?: string;
  body?: unknown;
} = {}) {
  return new Request(`http://localhost${path}`, {
    method,
    headers: {
      ...(options.token ? { "X-Workspace-Token": options.token } : {}),
      ...(options.aiKey ? { "X-AI-Model-Key": options.aiKey } : {}),
      ...(options.body ? { "Content-Type": "application/json" } : {}),
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  });
}

describe("E7-S1: end-to-end happy path (scripted fake LLM client)", () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  it("drives workspace -> project -> interview to convergence -> generate spec -> fetch latest", async () => {
    const workspace = {
      id: "workspace-e2e",
      magic_token: "e2e-token",
      created_at: new Date(),
    };
    const project = {
      id: "project-e2e",
      workspace_id: "workspace-e2e",
      name: "E2E Test Project",
      status: "active",
      created_at: new Date(),
    };

    // In-memory conversation state that our mocked repository reads/writes,
    // so each chat turn sees the result of the previous one.
    let conversation = {
      id: "conversation-e2e",
      project_id: project.id,
      messages: [] as Anthropic.MessageParam[],
      interview_state: { satisfiedSectionIds: [] as string[] },
    };

    repository.createWorkspace.mockResolvedValue(workspace);
    repository.getWorkspaceByMagicToken.mockResolvedValue(workspace);
    repository.createProject.mockResolvedValue(project);
    repository.getProjectInWorkspace.mockResolvedValue(project);
    repository.getOrCreateConversation.mockImplementation(async () => conversation);
    repository.saveConversationTurn.mockImplementation(
      async (_projectId: string, messages: Anthropic.MessageParam[], state: { satisfiedSectionIds: string[] }) => {
        conversation = { ...conversation, messages, interview_state: state };
      }
    );

    // 1. Create workspace
    const workspaceResponse = await createWorkspaceRoute();
    expect(workspaceResponse.status).toBe(201);

    // 2. Create project
    const projectResponse = await createProjectRoute(
      request("POST", "/api/projects", {
        token: "e2e-token",
        body: { name: "E2E Test Project" },
      })
    );
    expect(projectResponse.status).toBe(201);

    // 3. Run chat turns until convergence (one section satisfied per turn)
    let converged = false;
    let safetyCounter = 0;
    while (!converged && safetyCounter < SPEC_SECTIONS.length + 2) {
      const chatResponse = await chatRoute(
        request("POST", "/api/chat", {
          token: "e2e-token",
          aiKey: "fake-key",
          body: { projectId: project.id, message: "Some answer." },
        })
      );
      expect(chatResponse.status).toBe(200);
      const body = await chatResponse.json();
      converged = body.converged;
      safetyCounter += 1;
    }
    expect(converged).toBe(true);

    // 4. Generate spec
    repository.createSpecVersion.mockImplementation(
      async (projectId: string, markdown: string, sections: Record<string, string>) => ({
        id: "spec-e2e",
        project_id: projectId,
        markdown,
        schema_json: sections,
        version: 1,
        created_at: new Date(),
      })
    );

    const generateResponse = await generateSpecRoute(
      request("POST", "/api/spec", {
        token: "e2e-token",
        aiKey: "fake-key",
        body: { projectId: project.id },
      })
    );
    expect(generateResponse.status).toBe(201);
    const generated = await generateResponse.json();
    expect(generated.version).toBe(1);
    expect(generated.markdown).toContain("Fake E2E Spec");

    // 5. Fetch latest spec
    repository.getLatestSpec.mockResolvedValue({
      id: "spec-e2e",
      project_id: project.id,
      markdown: generated.markdown,
      schema_json: {},
      version: 1,
      created_at: new Date(),
    });

    const fetchResponse = await getSpecRoute(
      request("GET", `/api/spec?projectId=${project.id}`, { token: "e2e-token" })
    );
    expect(fetchResponse.status).toBe(200);
    const fetched = await fetchResponse.json();
    expect(fetched.version).toBe(1);
  });
});